import { config } from 'dotenv';
config();

import '@/ai/flows/ai-content-outline-tool.ts';
import '@/ai/flows/bull-case-flow.ts';
import '@/ai/flows/bear-case-flow.ts';
import '@/ai/flows/risk-detection-flow.ts';
import '@/ai/flows/catalyst-detection-flow.ts';
import '@/ai/flows/earnings-summary-flow.ts';
import '@/ai/flows/macro-summary-flow.ts';
import '@/ai/flows/sector-overview-flow.ts';
import '@/ai/flows/social-sentiment-flow.ts';
import '@/ai/flows/daily-briefing-flow.ts';
import '@/ai/flows/weekly-digest-flow.ts';
import '@/ai/flows/asset-comparison-flow.ts';
import '@/ai/flows/multi-asset-comparison-flow.ts';
import '@/ai/flows/ai-news-summary-flow.ts';
import '@/ai/flows/trend-explanation-flow.ts';
import '@/ai/flows/automated-recap-flow.ts';
import '@/ai/flows/model-performance-flow.ts';
